export type EventType =
  | "PLAYER_DIED"
  | "PLAYER_HP_CHANGED"
  | "CURSE_ADDED"
  | "GOLD_CHANGED"
  | "RELIC_ACQUIRED"
  | "BOSS_DEFEATED"
  | "ACT_COMPLETED"
  | "PLAYER_MUTED"
  | "VOTE_CAST"
  | "POWER_USED";